ERROR 2025-09-25 13:28:47,616 logging_utility Error response: Response: 401 for GET /api/user/me/ by Anonymous (Duration: 0.00s)
ERROR 2025-09-25 13:28:50,302 logging_utility Error response: Response: 400 for POST /api/notes/ by testuser (Duration: 0.01s)
ERROR 2025-09-25 13:28:51,682 logging_utility Error response: Response: 401 for POST /api/notes/ by Anonymous (Duration: 0.00s)
ERROR 2025-09-25 13:28:53,091 logging_utility Error deleting note for admin admin - Exception: No Note matches the given query.
Traceback (most recent call last):
  File "C:\Users\Fabian Puentes\Desktop\login\env\Lib\site-packages\django\shortcuts.py", line 90, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Fabian Puentes\Desktop\login\env\Lib\site-packages\django\db\models\query.py", line 633, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
api.models.Note.DoesNotExist: Note matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Fabian Puentes\Desktop\login\backend\api\views.py", line 116, in destroy
    note = self.get_object()
  File "C:\Users\Fabian Puentes\Desktop\login\env\Lib\site-packages\rest_framework\generics.py", line 100, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "C:\Users\Fabian Puentes\Desktop\login\env\Lib\site-packages\rest_framework\generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "C:\Users\Fabian Puentes\Desktop\login\env\Lib\site-packages\django\shortcuts.py", line 92, in get_object_or_404
    raise Http404(
        "No %s matches the given query." % queryset.model._meta.object_name
    )
django.http.response.Http404: No Note matches the given query.
ERROR 2025-09-25 13:28:55,003 logging_utility Error response: Response: 500 for DELETE /api/notes/delete/9999/ by admin (Duration: 1.91s)
ERROR 2025-09-25 13:29:00,610 logging_utility Error response: Response: 401 for GET /api/notes/ by Anonymous (Duration: 0.00s)
ERROR 2025-09-25 13:29:08,634 logging_utility Error response: Response: 400 for POST /api/user/register/ by Anonymous (Duration: 0.01s)
ERROR 2025-09-25 13:29:08,646 logging_utility Error response: Response: 400 for POST /api/user/register/ by Anonymous (Duration: 0.01s)
ERROR 2025-09-25 18:43:53,818 logging_utility Error response: Response: 401 for GET /api/user/me/ by Anonymous (Duration: 0.00s)
ERROR 2025-09-25 18:43:56,205 logging_utility Error response: Response: 400 for POST /api/notes/ by testuser (Duration: 0.00s)
ERROR 2025-09-25 18:43:57,398 logging_utility Error response: Response: 401 for POST /api/notes/ by Anonymous (Duration: 0.00s)
ERROR 2025-09-25 18:57:03,295 logging_utility Error deleting note for admin admin - Exception: No Note matches the given query.
Traceback (most recent call last):
  File "C:\Users\Fabian Puentes\Desktop\login\env\Lib\site-packages\django\shortcuts.py", line 90, in get_object_or_404
    return queryset.get(*args, **kwargs)
           ~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\Fabian Puentes\Desktop\login\env\Lib\site-packages\django\db\models\query.py", line 633, in get
    raise self.model.DoesNotExist(
        "%s matching query does not exist." % self.model._meta.object_name
    )
api.models.Note.DoesNotExist: Note matching query does not exist.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Fabian Puentes\Desktop\login\backend\api\views.py", line 113, in destroy
    note = self.get_object()
  File "C:\Users\Fabian Puentes\Desktop\login\env\Lib\site-packages\rest_framework\generics.py", line 100, in get_object
    obj = get_object_or_404(queryset, **filter_kwargs)
  File "C:\Users\Fabian Puentes\Desktop\login\env\Lib\site-packages\rest_framework\generics.py", line 19, in get_object_or_404
    return _get_object_or_404(queryset, *filter_args, **filter_kwargs)
  File "C:\Users\Fabian Puentes\Desktop\login\env\Lib\site-packages\django\shortcuts.py", line 92, in get_object_or_404
    raise Http404(
        "No %s matches the given query." % queryset.model._meta.object_name
    )
django.http.response.Http404: No Note matches the given query.
ERROR 2025-09-25 18:57:03,959 logging_utility Error response: Response: 500 for DELETE /api/notes/delete/22/ by admin (Duration: 0.71s)
